SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `bd_autoescola` DEFAULT CHARACTER SET utf8 ;
USE `bd_autoescola` ;

-- -----------------------------------------------------
-- Table `bd_autoescola`.`tb_calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoescola`.`tb_calendario` (
  `ID_CALENDARIO` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_CALENDARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_autoescola`.`tb_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoescola`.`tb_carro` (
  `ANO_CARRO` VARCHAR(55) NOT NULL,
  `MARCA_CARRO` VARCHAR(55) NOT NULL,
  `MODELO_CARRO` VARCHAR(55) NOT NULL,
  `PLACA_CARRO` VARCHAR(55) NOT NULL,
  UNIQUE INDEX `PLACA_CARRO` (`PLACA_CARRO` ASC),
  PRIMARY KEY (`PLACA_CARRO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_autoescola`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoescola`.`tb_cliente` (
  `ID_CLIENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(255) NOT NULL,
  `DATANASCIMENTO_CLIENTE` VARCHAR(20) NOT NULL,
  `EMAIL_CLIENTE` VARCHAR(255) NULL DEFAULT NULL,
  `ESCOLARIDADE_CLIENTE` VARCHAR(20) NULL DEFAULT NULL,
  `TELEFONE_CLIENTE` VARCHAR(25) NULL DEFAULT NULL,
  `CELULAR_CLIENTE` VARCHAR(25) NULL DEFAULT NULL,
  `PROFISSAO_CLIENTE` VARCHAR(30) NULL DEFAULT NULL,
  `RG_CLIENTE` VARCHAR(30) NULL DEFAULT NULL,
  `CPF_CLIENTE` VARCHAR(30) NOT NULL,
  `SEXO_CLIENTE` VARCHAR(20) NOT NULL,
  `REGISTROCNH_CLIENTE` VARCHAR(30) NOT NULL,
  `VALIDADECNH_CLIENTE` VARCHAR(20) NOT NULL,
  `PRIMEIRACNH_CLIENTE` VARCHAR(20) NOT NULL,
  `LOGRADOURO_CLIENTE` VARCHAR(200) NOT NULL,
  `NUMERO_CLIENTE` VARCHAR(45) NOT NULL,
  `BAIRRO_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  `CEP_CLIENTE` VARCHAR(45) NOT NULL,
  `DATACADASTRO_CLIENTE` VARCHAR(45) NOT NULL,
  `PESQUISA1_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  `PESQUISA2_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  `PESQUISA3_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  `PESQUISA4_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  `OBSERVACAO_CLIENTE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  UNIQUE INDEX `NOME_CLIENTE` (`NOME_CLIENTE` ASC),
  UNIQUE INDEX `CPF_CLIENTE` (`CPF_CLIENTE` ASC),
  UNIQUE INDEX `REGISTROCNH_CLIENTE_UNIQUE` (`REGISTROCNH_CLIENTE` ASC),
  UNIQUE INDEX `EMAIL_CLIENTE` (`EMAIL_CLIENTE` ASC),
  UNIQUE INDEX `TELEFONE_CLIENTE` (`TELEFONE_CLIENTE` ASC),
  UNIQUE INDEX `CELULAR_CLIENTE` (`CELULAR_CLIENTE` ASC),
  UNIQUE INDEX `RG_CLIENTE` (`RG_CLIENTE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_autoescola`.`tb_instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoescola`.`tb_instrutor` (
  `ID_INSTRUTOR` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_INSTRUTOR` VARCHAR(200) NOT NULL,
  `DATA_INSTRUTOR` VARCHAR(20) NOT NULL,
  `CNH_INSTRUTOR` VARCHAR(50) NOT NULL,
  `VALIDADECNH_INSTRUTOR` VARCHAR(20) NOT NULL,
  `PRIMEIRACNH_INSTRUTOR` VARCHAR(20) NOT NULL,
  `RG_INSTRUTOR` VARCHAR(50) NULL DEFAULT NULL,
  `CPF_INSTRUTOR` VARCHAR(50) NOT NULL,
  `TELEFONE_INSTRUTOR` VARCHAR(50) NULL DEFAULT NULL,
  `CELULAR_INSTRUTOR` VARCHAR(50) NULL DEFAULT NULL,
  `STATUS_INSTRUTOR` VARCHAR(20) NOT NULL,
  `tb_carro_PLACA_CARRO` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`ID_INSTRUTOR`, `tb_carro_PLACA_CARRO`),
  UNIQUE INDEX `NOME_FUNCIONARIO_UNIQUE` (`NOME_INSTRUTOR` ASC),
  UNIQUE INDEX `CNH_FUNCIONARIO_UNIQUE` (`CNH_INSTRUTOR` ASC),
  UNIQUE INDEX `CPF_FUNCIONARIO_UNIQUE` (`CPF_INSTRUTOR` ASC),
  UNIQUE INDEX `RG_FUNCIONARIO_UNIQUE` (`RG_INSTRUTOR` ASC),
  INDEX `fk_tb_instrutor_tb_carro_idx` (`tb_carro_PLACA_CARRO` ASC),
  CONSTRAINT `fk_tb_instrutor_tb_carro`
    FOREIGN KEY (`tb_carro_PLACA_CARRO`)
    REFERENCES `bd_autoescola`.`tb_carro` (`PLACA_CARRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_autoescola`.`tb_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoescola`.`tb_login` (
  `ID_LOGIN` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_LOGIN` VARCHAR(50) NOT NULL DEFAULT 'josiene',
  `SENHA_LOGIN` VARCHAR(50) NOT NULL DEFAULT 'correntina',
  PRIMARY KEY (`ID_LOGIN`),
  UNIQUE INDEX `USUARIO_LOGIN` (`USUARIO_LOGIN` ASC),
  UNIQUE INDEX `SENHA_LOGIN` (`SENHA_LOGIN` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
